### ISSUE TITLE
回编译报错但没有指明文件，希望解答一下，谢谢！

### ISSUE THREAD

**Issue by nespjin** [FlymeOS/tools#16]
I: Using Apktool 2.2.2-6a4ae2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.IllegalStateException: Cannot get the location of a label that hasn't been placed yet.
	at org.jf.dexlib2.builder.Label.getLocation(Label.java:54)
	at org.jf.dexlib2.builder.Label.getCodeAddress(Label.java:48)
	at org.jf.dexlib2.builder.BuilderOffsetInstruction.internalGetCodeOffset(BuilderOffsetInstruction.java:60)
	at org.jf.dexlib2.builder.BuilderOffsetInstruction.getCodeOffset(BuilderOffsetInstruction.java:50)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:206)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:988)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:803)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:252)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:230)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:404)
	at brut.androlib.Androlib.buildSources(Androlib.java:335)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
/home/jin/flyme/build/main.mk:451: recipe for target 'out/obj/system/framework/services.jar' failed
make: *** [out/obj/system/framework/services.jar] Error 161

**Comment by nespjin** [comment]
希望官方能把工具优化一下，让它指出具体文件

**Comment by hexiaoshuai** [comment]
具体排查修改了什么在services.jar

**Comment by nespjin** [comment]
通过了但没有任何打印，应该不影响吧？
in@jin-virtual-machine:~/flyme/devices/4$ flyme services
>>> services


<<< services succeed

**Comment by hexiaoshuai** [comment]
flyme clean-services
