### ISSUE TITLE
Stuck at Pull boot and recovery,

### ISSUE THREAD

**Issue by ganixdev** [FlymeOS/tools#19]
Console Output:

root@innfinite4evr-A780LB:/media/innfinite4evr/AndroWorks_ext4/flyme/devices/merlin# flyme config
>>> config
>>> Check connecting state
>>> Check adb root state
>>> Kernel root ready, run adb root
adbd is already running as root
>>> Wait for the device to be online...
>>> device is online
>>> Root State: Kernal Root
>>> Setup the Makefile Begin!
>>> Set vendor_modify_jars: framework services telephony-common wifi-service
>>> Set DENSITY: xhdpi
>>> Set RESOLUTION: 720x1280
>>> Set vendor_saved_apps: Bluetooth BluetoothExt BluetoothMidiService HTMLViewer KeyChain PicoTts PrintSpooler Stk UserDictionaryProvider BackupRestoreConfirmation DefaultContainerService ExternalStorageProvider FMRadio FusedLocation InputDevices ProxyHandler SharedStorageBackup Shell
====================================================
Makefile Configuration:
    vendor_modify_jars := framework services telephony-common wifi-service
    vendor_saved_apps  := Bluetooth BluetoothExt BluetoothMidiService HTMLViewer KeyChain PicoTts PrintSpooler Stk UserDictionaryProvider BackupRestoreConfirmation DefaultContainerService ExternalStorageProvider FMRadio FusedLocation InputDevices ProxyHandler SharedStorageBackup Shell
    DENSITY            := xhdpi
    RESOLUTION         := 720x1280
====================================================
>>> Setup the Makefile Done!
Pull boot and recovery, It may take a few minutes, please wait....

I tried cheking pull_boot_recovery process and found tools/pull-boot_recovery is symlinked to -> tools/bootimgpack/pull_boot_recovery.py

itried exectuing this python script(pull_boot_recovery.py) with python2.7
and here is the output

innfinite4evr@innfinite4evr-A780LB:/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack$ python2.7 pull_boot_recovery.py
I/pull_boot_recovery: Begin pull boot and recovery, make sure your phone was connected and adb devices is fine!
I/pull_boot_recovery: It may take a few minutes, please wait....
I/adb: waiting for devices....

I/pull_boot_recovery: adb connect success.
Traceback (most recent call last):
  File "pull_boot_recovery.py", line 19, in <module>
    utils.PullUtils.pull(outDir)
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/utils.py", line 38, in pull
    if pull.do(outDir):
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/pull.py", line 93, in do
    adDict = p.getAdPartitions(pull.MIN_SIZE, pull.MAX_SIZE)
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/pull.py", line 45, in getAdPartitions
    adPt = AndroidFile(pull.PROC_PARTITIONS)
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/command.py", line 124, in __init__
    self.mShell = ShellFactory.getDefaultShell()
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/command.py", line 116, in getDefaultShell
    ShellFactory.mShell = ShellFactory.__getRootShell__()
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/command.py", line 100, in __getRootShell__
    subp = subprocess.Popen(["check-su"], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

After that i tried runnning the same script with python3
and here is th output 

innfinite4evr@innfinite4evr-A780LB:/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack$ python3 pull_boot_recovery.py
Traceback (most recent call last):
  File "pull_boot_recovery.py", line 10, in <module>
    from pull import utils
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/utils.py", line 11, in <module>
    from bootimgpack.pull.push import push
  File "/media/innfinite4evr/AndroWorks_ext4/flyme/tools/bootimgpack/pull/push.py", line 35
    print ">>> start flash %s from %s to %s" %(self.mDevice, self.mInFile, mp)
                                           ^
SyntaxError: invalid syntax

Whats the problem.............?
it is with python vesion ???
python -V give this
Python 2.7.12

Thanks devs your work on flyme os patchrom!!!

**Comment by hexiaoshuai** [comment]
Please wait patiently or manually place recovery.img and boot.img

**Comment by ganixdev** [comment]
Thanks did tour concern,
Please elaborate there manual method

**Comment by ganixdev** [comment]
*Thanks for your concern,
Please elaborate there manual method

**Comment by hexiaoshuai** [comment]
Don't worry, press Ctrl + C to exit and execute the following command
